### ISSUE TITLE
reflexive pronouns for inherently reflexive verbs are connected as obj instead of expl

### ISSUE THREAD

**Issue by fhennig** [UniversalDependencies/UD_German#2]
The documentation on [expl](http://universaldependencies.org/u/dep/all.html#al-u-dep/expl) says, that for verbs which are inherently reflexive, the reflexive pronoun should not be connected with dobj, respectively obj, but instead with expl. In german there are a few inherently reflexive verbs, such as "sich freuen" or "sich erkälten".

I found "Ich freue mich ..." where "mich" was connected as dobj (Sentence 1933, 1934, 1935). And there are more examples when searching for reflexive pronouns connected as objects.

I also didn't find any other word connected as expl, besides "es", that was the reason I found out about this.

**Comment by jnivre** [comment]
Thanks for raining this issue. The analysis of reflexives is one of the areas where we still have some inconsistencies in UD treebanks. The decision to analyze inherent reflexives using expl is rather recent, and since no one has been working on UD German lately, it has not been updated. My guess is that these should be changed to "refl", but it would be good to get that confirmed by someone more knowledgeable about German than me. :)

**Comment by dan-zeman** [comment]
I switched the reflexive dependents of a few verbs to `expl:pv` in b847792db2d3acac965418177fefd4103c5ffda2. Note that _freuen_ is not among them because it would require manual re-annotation. I agree that _er freut sich darauf_ (reflexive) is a different meaning from _das freut ihn_ (transitive) and they should be treated as two different (though homonymous) verbs; but they cannot be told apart automatically. And there seem to be a number of verbs that are predominantly reflexive but the irreflexive use cannot be excluded, although it is rare, obsolete or limited to certain dialects.
