### ISSUE TITLE
"Sie sind es" how to annotate

### ISSUE THREAD

**Issue by fhennig** [UniversalDependencies/UD_German#4]
I have a problem annotating this sentence:

"Sie sind es, die jetzt in der Regierung sitzen."

I think making "sind" the root and connecting "es" as an expletive makes sense, because "es" is an expletive here, it is not referring to anything as a pronoun.

The other version would be to make "es" the root and connect "sind" as "cop", which is usually done when "sind" is followed by a nonverbal predicate. But "es" is just taking the position of a predicate, it does not 'satisfy any of the semantic roles of the predicate', which is why it should not be the root of the sentence.

So the verb is just a copula, and the nonverbal predicate is just an expletive, which one should be the root of the sentence?

**Comment by jnivre** [comment]
My knowledge of German is very limited, but this looks like a cleft to me. Clefts were discussed in at the Uppsala meeting, but I am not sure any real conclusion was reached. I think we should reopen this discussion in the light of the new guidelines for copula constructions. In many languages, I think they should be grouped with existentials with locative modifiers ("there is food in the kitchen") with the "be" as the head. @dan-zeman @ftyers @manning

**Comment by amir-zeldes** [comment]
Not commenting on clefts in general, I think this situation actually should have 'es' as the root, because that's how I would analyze the alternative formulation:

Sie sind diejenigen, die jetzt in der Regierung sitzen.

The predicate is semantically 'the ones who sit in the government' in both cases. The question is just one of agreement. But I think it's clear in both cases "Sie" is the subject, and I don't think it's existential - it's actually symmetrically copular (the ones who are in government are you, and you are the ones who are in government). So although it's a little odd, I think 'es' is better than 'sind' as root (I'd suggest the same for: "Es sind Sie, die Sie sind ...", since agreement sind<>Sie shows this is the grammatical subject). Just my 2c though.

**Comment by dan-zeman** [comment]
I would definitely treat this as a copula. The predicate is represented by a pronoun, so what? Any nominal can be occasionally replaced by a pronoun. Syntactically it is parallel, as @amir-zeldes notes. Therefore my analysis would be:

nsubj(es, Sie)
cop(es, sind)
acl:relcl(es, sitzen)
nsubj(sitzen, die)

(There is the question whether the relative clause should be attached to _es_ or to _Sie_. The plural agreement again points to _Sie_ but since the content of the relative clause clearly is part of the predication, I lean towards attaching it to _es_.)

**Comment by fhennig** [comment]
Okay, thanks a lot!

**Comment by jnivre** [comment]
I am not sure I want to reopen this issue right now, but I think in the long run we need a different analysis of clefts for cross-linguistic parallelism. My claim about existential was misguided. Instead I agree with @amir-zeldes that they are equational constructions, with the (free) relative functioning as the predicate. Hence, by the exception for clausal predicates in copula constructions, they should probably be analysed like this (using an English example to avoid making incorrect claims about German):

It was John who played tennis
expl(was, it)
nsubj(john)
ccomp(was, played)

This analysis will generalise to pseudo-clefts (what John did was play tennis) and to corresponding structures in other languages. But this clearly requires more analysis and discussion so probably is an issue for v3.

**Comment by amir-zeldes** [comment]
@jnivre I think this can be fine for clefts (like a small clause - "it was the case: John played"). But I'm not sure I understand what you mean completely: what is John the nsubj of? Is it played? If so what is "who"? If this is equational, wouldn't we end up with two nsubj: John is subj of "John = who played tennis" (but the predicate head is still played) and 'who' is nsubj of played in the relative - so do we "John" and "who" attached to play?

Either way, I don't think we can always analyze correlate pronouns as expletives. The German example above isn't so different from an extraposed object clause with correlate pronoun (and Slavic has this too, e.g. Polish to ... co ([did] that ... what [I said]), or adverbial tak ... jak (thus ... how). In UD German I can find examples like:

```
Es geht nicht um das, was hier zwei Jugendliche geschrieben haben .
Lit. It goes not around that, what here two youths have written
"It's not a matter of what two teenagers have written"
```

In English we wouldn't need the 'that'. But in the German examples, the tree has:

nmod(geht,das)  [should now be 'obl']
acl(das,geschrieben) [that -> wrote as relative clause]
dobj(geschrieben,was) [wrote -> what as obj relative]

If the 'it' in the OP here is 'expl', then shouldn't that apply here too? I would be against that, since it suggests that any relative expansion to extrapose a heavy clause involves expletives. Would we apply the same to this:

```
Ich habe das so gemacht, wie ich wollte.
"I did it thus, like I wanted."
(same e.g. for Polish: zrobiłem to tak, jak chciałem)
```

Would the 'so' "thus" also be an expletive? If not, then I think the 'es' in the OP should also not be expletive.

**Comment by gossebouma** [comment]
I think I am with @amir-zeldes  and @dan-zeman  here, if only because this seems to be in line with the way we analyzed such constructions in our Lassy Dutch treebank. eg

 "maar het is de trainer die beslist wie er speelt en wie niet"
_but it is the coach who decides who is playing and who isn't_
[lassy tree](http://zardoz.service.rug.nl:8067/tree?db=lassysmall&names=true&mwu=false&arch=/net/corpora/paqu/lassysmallmeta.dact&file=dpc-rou-000349-nl-sen.p.2.s.18.xml&global=true&marknodes=8)

Here, the epletive 'het' is analyzed as a predicative complement of the copula, and the relative clause is attached to the expletive. In UD terms that would probably mean 

nsubj(trainer,het)
cop(is,het)
acl:relcl(beslist,het)

**Comment by dan-zeman** [comment]
@gossebouma : agreed, except that we usually show the relations as

label(parent, child)

while you seem to have reversed the direction.
