### ISSUE TITLE
Comparative "wie"

### ISSUE THREAD

**Issue by fhennig** [UniversalDependencies/UD_German#8]
"In dem Termin lief alles wie besprochen."

I am unsure how this should be annotated. I found the sentence in the UD treebank, with

    wie >cc besprochen
    besprochen >conj lief

But I think maybe

    wie >mark besprochen
    besprochen >advcl lief

is the correct annotation?

I found English sentences where "as conceived" is attached that way and I think it is the same phenomenon. 

A different sentence:  "Ich bin genauso alt wie Lukas."

I think here it should be 

    wie >case Lukas
    Lukas >obl alt
    bin >cop alt
    genauso >advmod alt
    Ich >subj alt

So if the comparative is using a noun as a comparison it can be a simple obl or nmod. This is in line with the English annotations.

**Comment by jnivre** [comment]
I don't really know German, but your arguments make total sense to me. Comparatives and related constructions are tricky in general, because they are often elliptical. Therefore, it can be discussed whether the nominal case ("Lukas") should be "obl" or "advcl" (with promotion of subject). But using "obl" when possible is a simple and straightforward solution.

**Comment by dan-zeman** [comment]
The "wie besprochen" definitely is not coordination. I will look into fixing the bug.

I think the relation between _alt_ and _Lukas_ should not be `advcl` because the guidelines say somewhere that if the standard of comparison is a simple nominal, we do not treat it as ellipsis. So probably it should be `obl` (there is another question whether `obl` or `nmod` and I am a bit uncomfortable with the preference for `obl` but it seems to be what the majority is doing).

**Comment by dan-zeman** [comment]
Fixed in https://github.com/UniversalDependencies/UD_German/commit/26dceb12360d3ca5d79cc823f3b7612d5e11c8f1.
